export const hangjungdong = {
  postLocation1: [
    { postLocation1: "서울특별시", codeNm: "서울특별시" },
    { postLocation1: "부산광역시", codeNm: "부산광역시" },
    { postLocation1: "대구광역시", codeNm: "대구광역시" },
    { postLocation1: "인천광역시", codeNm: "인천광역시" },
    { postLocation1: "광주광역시", codeNm: "광주광역시" },
    { postLocation1: "대전광역시", codeNm: "대전광역시" },
    { postLocation1: "울산광역시", codeNm: "울산광역시" },
    { postLocation1: "세종특별자치시", codeNm: "세종특별자치시" },
    { postLocation1: "경기도", codeNm: "경기도" },
    { postLocation1: "강원도", codeNm: "강원도" },
    { postLocation1: "충청북도", codeNm: "충청북도" },
    { postLocation1: "충청남도", codeNm: "충청남도" },
    { postLocation1: "전라북도", codeNm: "전라북도" },
    { postLocation1: "전라남도", codeNm: "전라남도" },
    { postLocation1: "경상북도", codeNm: "경상북도" },
    { postLocation1: "경상남도", codeNm: "경상남도" },
    { postLocation1: "제주특별자치도", codeNm: "제주특별자치도" },
  ],
  postLocation2: [
    { postLocation1: "서울특별시", postLocation2: "110", codeNm: "종로구" },
    { postLocation1: "서울특별시", postLocation2: "140", codeNm: "중구" },
    { postLocation1: "서울특별시", postLocation2: "170", codeNm: "용산구" },
    { postLocation1: "서울특별시", postLocation2: "200", codeNm: "성동구" },
    { postLocation1: "서울특별시", postLocation2: "215", codeNm: "광진구" },
    { postLocation1: "서울특별시", postLocation2: "230", codeNm: "동대문구" },
    { postLocation1: "서울특별시", postLocation2: "260", codeNm: "중랑구" },
    { postLocation1: "서울특별시", postLocation2: "290", codeNm: "성북구" },
    { postLocation1: "서울특별시", postLocation2: "305", codeNm: "강북구" },
    { postLocation1: "서울특별시", postLocation2: "320", codeNm: "도봉구" },
    { postLocation1: "서울특별시", postLocation2: "350", codeNm: "노원구" },
    { postLocation1: "서울특별시", postLocation2: "380", codeNm: "은평구" },
    { postLocation1: "서울특별시", postLocation2: "410", codeNm: "서대문구" },
    { postLocation1: "서울특별시", postLocation2: "440", codeNm: "마포구" },
    { postLocation1: "서울특별시", postLocation2: "470", codeNm: "양천구" },
    { postLocation1: "서울특별시", postLocation2: "500", codeNm: "강서구" },
    { postLocation1: "서울특별시", postLocation2: "530", codeNm: "구로구" },
    { postLocation1: "서울특별시", postLocation2: "545", codeNm: "금천구" },
    { postLocation1: "서울특별시", postLocation2: "560", codeNm: "영등포구" },
    { postLocation1: "서울특별시", postLocation2: "590", codeNm: "동작구" },
    { postLocation1: "서울특별시", postLocation2: "620", codeNm: "관악구" },
    { postLocation1: "서울특별시", postLocation2: "650", codeNm: "서초구" },
    { postLocation1: "서울특별시", postLocation2: "680", codeNm: "강남구" },
    { postLocation1: "서울특별시", postLocation2: "710", codeNm: "송파구" },
    { postLocation1: "서울특별시", postLocation2: "740", codeNm: "강동구" },
    { postLocation1: "부산광역시", postLocation2: "110", codeNm: "중구" },
    { postLocation1: "부산광역시", postLocation2: "140", codeNm: "서구" },
    { postLocation1: "부산광역시", postLocation2: "170", codeNm: "동구" },
    { postLocation1: "부산광역시", postLocation2: "200", codeNm: "영도구" },
    { postLocation1: "부산광역시", postLocation2: "230", codeNm: "부산진구" },
    { postLocation1: "부산광역시", postLocation2: "260", codeNm: "동래구" },
    { postLocation1: "부산광역시", postLocation2: "290", codeNm: "남구" },
    { postLocation1: "부산광역시", postLocation2: "320", codeNm: "북구" },
    { postLocation1: "부산광역시", postLocation2: "350", codeNm: "해운대구" },
    { postLocation1: "부산광역시", postLocation2: "380", codeNm: "사하구" },
    { postLocation1: "부산광역시", postLocation2: "410", codeNm: "금정구" },
    { postLocation1: "부산광역시", postLocation2: "440", codeNm: "강서구" },
    { postLocation1: "부산광역시", postLocation2: "470", codeNm: "연제구" },
    { postLocation1: "부산광역시", postLocation2: "500", codeNm: "수영구" },
    { postLocation1: "부산광역시", postLocation2: "530", codeNm: "사상구" },
    { postLocation1: "부산광역시", postLocation2: "710", codeNm: "기장군" },
    { postLocation1: "대구광역시", postLocation2: "110", codeNm: "중구" },
    { postLocation1: "대구광역시", postLocation2: "140", codeNm: "동구" },
    { postLocation1: "대구광역시", postLocation2: "170", codeNm: "서구" },
    { postLocation1: "대구광역시", postLocation2: "200", codeNm: "남구" },
    { postLocation1: "대구광역시", postLocation2: "230", codeNm: "북구" },
    { postLocation1: "대구광역시", postLocation2: "260", codeNm: "수성구" },
    { postLocation1: "대구광역시", postLocation2: "290", codeNm: "달서구" },
    { postLocation1: "대구광역시", postLocation2: "710", codeNm: "달성군" },
    { postLocation1: "인천광역시", postLocation2: "110", codeNm: "중구" },
    { postLocation1: "인천광역시", postLocation2: "140", codeNm: "동구" },
    { postLocation1: "인천광역시", postLocation2: "177", codeNm: "미추홀구" },
    { postLocation1: "인천광역시", postLocation2: "185", codeNm: "연수구" },
    { postLocation1: "인천광역시", postLocation2: "200", codeNm: "남동구" },
    { postLocation1: "인천광역시", postLocation2: "237", codeNm: "부평구" },
    { postLocation1: "인천광역시", postLocation2: "245", codeNm: "계양구" },
    { postLocation1: "인천광역시", postLocation2: "260", codeNm: "서구" },
    { postLocation1: "인천광역시", postLocation2: "710", codeNm: "강화군" },
    { postLocation1: "인천광역시", postLocation2: "720", codeNm: "옹진군" },
    { postLocation1: "광주광역시", postLocation2: "110", codeNm: "동구" },
    { postLocation1: "광주광역시", postLocation2: "140", codeNm: "서구" },
    { postLocation1: "광주광역시", postLocation2: "155", codeNm: "남구" },
    { postLocation1: "광주광역시", postLocation2: "170", codeNm: "북구" },
    { postLocation1: "광주광역시", postLocation2: "200", codeNm: "광산구" },
    { postLocation1: "대전광역시", postLocation2: "110", codeNm: "동구" },
    { postLocation1: "대전광역시", postLocation2: "140", codeNm: "중구" },
    { postLocation1: "대전광역시", postLocation2: "170", codeNm: "서구" },
    { postLocation1: "대전광역시", postLocation2: "200", codeNm: "유성구" },
    { postLocation1: "대전광역시", postLocation2: "230", codeNm: "대덕구" },
    { postLocation1: "울산광역시", postLocation2: "110", codeNm: "중구" },
    { postLocation1: "울산광역시", postLocation2: "140", codeNm: "남구" },
    { postLocation1: "울산광역시", postLocation2: "170", codeNm: "동구" },
    { postLocation1: "울산광역시", postLocation2: "200", codeNm: "북구" },
    { postLocation1: "울산광역시", postLocation2: "710", codeNm: "울주군" },
    {
      postLocation1: "세종특별자치시",
      postLocation2: "110",
      codeNm: "세종특별자치시",
    },
    { postLocation1: "경기도", postLocation2: "110", codeNm: "수원시" },
    { postLocation1: "경기도", postLocation2: "111", codeNm: "수원시 장안구" },
    { postLocation1: "경기도", postLocation2: "113", codeNm: "수원시 권선구" },
    { postLocation1: "경기도", postLocation2: "115", codeNm: "수원시 팔달구" },
    { postLocation1: "경기도", postLocation2: "117", codeNm: "수원시 영통구" },
    { postLocation1: "경기도", postLocation2: "130", codeNm: "성남시" },
    { postLocation1: "경기도", postLocation2: "131", codeNm: "성남시 수정구" },
    { postLocation1: "경기도", postLocation2: "133", codeNm: "성남시 중원구" },
    { postLocation1: "경기도", postLocation2: "135", codeNm: "성남시 분당구" },
    { postLocation1: "경기도", postLocation2: "150", codeNm: "의정부시" },
    { postLocation1: "경기도", postLocation2: "170", codeNm: "안양시" },
    { postLocation1: "경기도", postLocation2: "171", codeNm: "안양시 만안구" },
    { postLocation1: "경기도", postLocation2: "173", codeNm: "안양시 동안구" },
    { postLocation1: "경기도", postLocation2: "190", codeNm: "부천시" },
    { postLocation1: "경기도", postLocation2: "210", codeNm: "광명시" },
    { postLocation1: "경기도", postLocation2: "220", codeNm: "평택시" },
    { postLocation1: "경기도", postLocation2: "222", codeNm: "송탄출장소" },
    { postLocation1: "경기도", postLocation2: "224", codeNm: "안중출장소" },
    { postLocation1: "경기도", postLocation2: "250", codeNm: "동두천시" },
    { postLocation1: "경기도", postLocation2: "270", codeNm: "안산시" },
    { postLocation1: "경기도", postLocation2: "271", codeNm: "안산시 상록구" },
    { postLocation1: "경기도", postLocation2: "273", codeNm: "안산시 단원구" },
    { postLocation1: "경기도", postLocation2: "280", codeNm: "고양시" },
    { postLocation1: "경기도", postLocation2: "281", codeNm: "고양시 덕양구" },
    {
      postLocation1: "경기도",
      postLocation2: "285",
      codeNm: "고양시 일산동구",
    },
    {
      postLocation1: "경기도",
      postLocation2: "287",
      codeNm: "고양시 일산서구",
    },
    { postLocation1: "경기도", postLocation2: "290", codeNm: "과천시" },
    { postLocation1: "경기도", postLocation2: "310", codeNm: "구리시" },
    { postLocation1: "경기도", postLocation2: "360", codeNm: "남양주시" },
    { postLocation1: "경기도", postLocation2: "370", codeNm: "오산시" },
    { postLocation1: "경기도", postLocation2: "390", codeNm: "시흥시" },
    { postLocation1: "경기도", postLocation2: "410", codeNm: "군포시" },
    { postLocation1: "경기도", postLocation2: "430", codeNm: "의왕시" },
    { postLocation1: "경기도", postLocation2: "450", codeNm: "하남시" },
    { postLocation1: "경기도", postLocation2: "460", codeNm: "용인시" },
    { postLocation1: "경기도", postLocation2: "461", codeNm: "용인시 처인구" },
    { postLocation1: "경기도", postLocation2: "463", codeNm: "용인시 기흥구" },
    { postLocation1: "경기도", postLocation2: "465", codeNm: "용인시 수지구" },
    { postLocation1: "경기도", postLocation2: "480", codeNm: "파주시" },
    { postLocation1: "경기도", postLocation2: "500", codeNm: "이천시" },
    { postLocation1: "경기도", postLocation2: "550", codeNm: "안성시" },
    { postLocation1: "경기도", postLocation2: "570", codeNm: "김포시" },
    { postLocation1: "경기도", postLocation2: "590", codeNm: "화성시" },
    { postLocation1: "경기도", postLocation2: "610", codeNm: "광주시" },
    { postLocation1: "경기도", postLocation2: "630", codeNm: "양주시" },
    { postLocation1: "경기도", postLocation2: "650", codeNm: "포천시" },
    { postLocation1: "경기도", postLocation2: "670", codeNm: "여주시" },
    { postLocation1: "경기도", postLocation2: "800", codeNm: "연천군" },
    { postLocation1: "경기도", postLocation2: "820", codeNm: "가평군" },
    { postLocation1: "경기도", postLocation2: "830", codeNm: "양평군" },
    { postLocation1: "강원도", postLocation2: "110", codeNm: "춘천시" },
    { postLocation1: "강원도", postLocation2: "130", codeNm: "원주시" },
    { postLocation1: "강원도", postLocation2: "150", codeNm: "강릉시" },
    { postLocation1: "강원도", postLocation2: "170", codeNm: "동해시" },
    { postLocation1: "강원도", postLocation2: "190", codeNm: "태백시" },
    { postLocation1: "강원도", postLocation2: "210", codeNm: "속초시" },
    { postLocation1: "강원도", postLocation2: "230", codeNm: "삼척시" },
    { postLocation1: "강원도", postLocation2: "720", codeNm: "홍천군" },
    { postLocation1: "강원도", postLocation2: "730", codeNm: "횡성군" },
    { postLocation1: "강원도", postLocation2: "750", codeNm: "영월군" },
    { postLocation1: "강원도", postLocation2: "760", codeNm: "평창군" },
    { postLocation1: "강원도", postLocation2: "770", codeNm: "정선군" },
    { postLocation1: "강원도", postLocation2: "780", codeNm: "철원군" },
    { postLocation1: "강원도", postLocation2: "790", codeNm: "화천군" },
    { postLocation1: "강원도", postLocation2: "800", codeNm: "양구군" },
    { postLocation1: "강원도", postLocation2: "810", codeNm: "인제군" },
    { postLocation1: "강원도", postLocation2: "820", codeNm: "고성군" },
    { postLocation1: "강원도", postLocation2: "830", codeNm: "양양군" },
    { postLocation1: "충청북도", postLocation2: "110", codeNm: "청주시" },
    {
      postLocation1: "충청북도",
      postLocation2: "111",
      codeNm: "청주시 상당구",
    },
    {
      postLocation1: "충청북도",
      postLocation2: "112",
      codeNm: "청주시 서원구",
    },
    {
      postLocation1: "충청북도",
      postLocation2: "113",
      codeNm: "청주시 흥덕구",
    },
    {
      postLocation1: "충청북도",
      postLocation2: "114",
      codeNm: "청주시 청원구",
    },
    { postLocation1: "충청북도", postLocation2: "130", codeNm: "충주시" },
    { postLocation1: "충청북도", postLocation2: "150", codeNm: "제천시" },
    { postLocation1: "충청북도", postLocation2: "720", codeNm: "보은군" },
    { postLocation1: "충청북도", postLocation2: "730", codeNm: "옥천군" },
    { postLocation1: "충청북도", postLocation2: "740", codeNm: "영동군" },
    { postLocation1: "충청북도", postLocation2: "745", codeNm: "증평군" },
    { postLocation1: "충청북도", postLocation2: "750", codeNm: "진천군" },
    { postLocation1: "충청북도", postLocation2: "760", codeNm: "괴산군" },
    { postLocation1: "충청북도", postLocation2: "770", codeNm: "음성군" },
    { postLocation1: "충청북도", postLocation2: "800", codeNm: "단양군" },
    { postLocation1: "충청남도", postLocation2: "130", codeNm: "천안시" },
    {
      postLocation1: "충청남도",
      postLocation2: "131",
      codeNm: "천안시 동남구",
    },
    {
      postLocation1: "충청남도",
      postLocation2: "133",
      codeNm: "천안시 서북구",
    },
    { postLocation1: "충청남도", postLocation2: "150", codeNm: "공주시" },
    { postLocation1: "충청남도", postLocation2: "180", codeNm: "보령시" },
    { postLocation1: "충청남도", postLocation2: "200", codeNm: "아산시" },
    { postLocation1: "충청남도", postLocation2: "210", codeNm: "서산시" },
    { postLocation1: "충청남도", postLocation2: "230", codeNm: "논산시" },
    { postLocation1: "충청남도", postLocation2: "250", codeNm: "계룡시" },
    { postLocation1: "충청남도", postLocation2: "270", codeNm: "당진시" },
    { postLocation1: "충청남도", postLocation2: "710", codeNm: "금산군" },
    { postLocation1: "충청남도", postLocation2: "760", codeNm: "부여군" },
    { postLocation1: "충청남도", postLocation2: "770", codeNm: "서천군" },
    { postLocation1: "충청남도", postLocation2: "790", codeNm: "청양군" },
    { postLocation1: "충청남도", postLocation2: "800", codeNm: "홍성군" },
    { postLocation1: "충청남도", postLocation2: "810", codeNm: "예산군" },
    { postLocation1: "충청남도", postLocation2: "825", codeNm: "태안군" },
    { postLocation1: "전라북도", postLocation2: "110", codeNm: "전주시" },
    {
      postLocation1: "전라북도",
      postLocation2: "111",
      codeNm: "전주시 완산구",
    },
    {
      postLocation1: "전라북도",
      postLocation2: "113",
      codeNm: "전주시 덕진구",
    },
    { postLocation1: "전라북도", postLocation2: "130", codeNm: "군산시" },
    { postLocation1: "전라북도", postLocation2: "140", codeNm: "익산시" },
    { postLocation1: "전라북도", postLocation2: "180", codeNm: "정읍시" },
    { postLocation1: "전라북도", postLocation2: "190", codeNm: "남원시" },
    { postLocation1: "전라북도", postLocation2: "210", codeNm: "김제시" },
    { postLocation1: "전라북도", postLocation2: "710", codeNm: "완주군" },
    { postLocation1: "전라북도", postLocation2: "720", codeNm: "진안군" },
    { postLocation1: "전라북도", postLocation2: "730", codeNm: "무주군" },
    { postLocation1: "전라북도", postLocation2: "740", codeNm: "장수군" },
    { postLocation1: "전라북도", postLocation2: "750", codeNm: "임실군" },
    { postLocation1: "전라북도", postLocation2: "770", codeNm: "순창군" },
    { postLocation1: "전라북도", postLocation2: "790", codeNm: "고창군" },
    { postLocation1: "전라북도", postLocation2: "800", codeNm: "부안군" },
    { postLocation1: "전라남도", postLocation2: "110", codeNm: "목포시" },
    { postLocation1: "전라남도", postLocation2: "130", codeNm: "여수시" },
    { postLocation1: "전라남도", postLocation2: "150", codeNm: "순천시" },
    { postLocation1: "전라남도", postLocation2: "170", codeNm: "나주시" },
    { postLocation1: "전라남도", postLocation2: "230", codeNm: "광양시" },
    { postLocation1: "전라남도", postLocation2: "710", codeNm: "담양군" },
    { postLocation1: "전라남도", postLocation2: "720", codeNm: "곡성군" },
    { postLocation1: "전라남도", postLocation2: "730", codeNm: "구례군" },
    { postLocation1: "전라남도", postLocation2: "770", codeNm: "고흥군" },
    { postLocation1: "전라남도", postLocation2: "780", codeNm: "보성군" },
    { postLocation1: "전라남도", postLocation2: "790", codeNm: "화순군" },
    { postLocation1: "전라남도", postLocation2: "800", codeNm: "장흥군" },
    { postLocation1: "전라남도", postLocation2: "810", codeNm: "강진군" },
    { postLocation1: "전라남도", postLocation2: "820", codeNm: "해남군" },
    { postLocation1: "전라남도", postLocation2: "830", codeNm: "영암군" },
    { postLocation1: "전라남도", postLocation2: "840", codeNm: "무안군" },
    { postLocation1: "전라남도", postLocation2: "860", codeNm: "함평군" },
    { postLocation1: "전라남도", postLocation2: "870", codeNm: "영광군" },
    { postLocation1: "전라남도", postLocation2: "880", codeNm: "장성군" },
    { postLocation1: "전라남도", postLocation2: "890", codeNm: "완도군" },
    { postLocation1: "전라남도", postLocation2: "900", codeNm: "진도군" },
    { postLocation1: "전라남도", postLocation2: "910", codeNm: "신안군" },
    { postLocation1: "경상북도", postLocation2: "110", codeNm: "포항시" },
    { postLocation1: "경상북도", postLocation2: "111", codeNm: "포항시 남구" },
    { postLocation1: "경상북도", postLocation2: "113", codeNm: "포항시 북구" },
    { postLocation1: "경상북도", postLocation2: "130", codeNm: "경주시" },
    { postLocation1: "경상북도", postLocation2: "150", codeNm: "김천시" },
    { postLocation1: "경상북도", postLocation2: "170", codeNm: "안동시" },
    { postLocation1: "경상북도", postLocation2: "190", codeNm: "구미시" },
    { postLocation1: "경상북도", postLocation2: "210", codeNm: "영주시" },
    { postLocation1: "경상북도", postLocation2: "230", codeNm: "영천시" },
    { postLocation1: "경상북도", postLocation2: "250", codeNm: "상주시" },
    { postLocation1: "경상북도", postLocation2: "280", codeNm: "문경시" },
    { postLocation1: "경상북도", postLocation2: "290", codeNm: "경산시" },
    { postLocation1: "경상북도", postLocation2: "720", codeNm: "군위군" },
    { postLocation1: "경상북도", postLocation2: "730", codeNm: "의성군" },
    { postLocation1: "경상북도", postLocation2: "750", codeNm: "청송군" },
    { postLocation1: "경상북도", postLocation2: "760", codeNm: "영양군" },
    { postLocation1: "경상북도", postLocation2: "770", codeNm: "영덕군" },
    { postLocation1: "경상북도", postLocation2: "820", codeNm: "청도군" },
    { postLocation1: "경상북도", postLocation2: "830", codeNm: "고령군" },
    { postLocation1: "경상북도", postLocation2: "840", codeNm: "성주군" },
    { postLocation1: "경상북도", postLocation2: "850", codeNm: "칠곡군" },
    { postLocation1: "경상북도", postLocation2: "900", codeNm: "예천군" },
    { postLocation1: "경상북도", postLocation2: "920", codeNm: "봉화군" },
    { postLocation1: "경상북도", postLocation2: "930", codeNm: "울진군" },
    { postLocation1: "경상북도", postLocation2: "940", codeNm: "울릉군" },
    { postLocation1: "경상남도", postLocation2: "120", codeNm: "창원시" },
    {
      postLocation1: "경상남도",
      postLocation2: "121",
      codeNm: "창원시 의창구",
    },
    {
      postLocation1: "경상남도",
      postLocation2: "123",
      codeNm: "창원시 성산구",
    },
    {
      postLocation1: "경상남도",
      postLocation2: "125",
      codeNm: "창원시 마산합포구",
    },
    {
      postLocation1: "경상남도",
      postLocation2: "127",
      codeNm: "창원시 마산회원구",
    },
    {
      postLocation1: "경상남도",
      postLocation2: "129",
      codeNm: "창원시 진해구",
    },
    { postLocation1: "경상남도", postLocation2: "170", codeNm: "진주시" },
    { postLocation1: "경상남도", postLocation2: "220", codeNm: "통영시" },
    { postLocation1: "경상남도", postLocation2: "240", codeNm: "사천시" },
    { postLocation1: "경상남도", postLocation2: "250", codeNm: "김해시" },
    { postLocation1: "경상남도", postLocation2: "270", codeNm: "밀양시" },
    { postLocation1: "경상남도", postLocation2: "310", codeNm: "거제시" },
    { postLocation1: "경상남도", postLocation2: "330", codeNm: "양산시" },
    { postLocation1: "경상남도", postLocation2: "720", codeNm: "의령군" },
    { postLocation1: "경상남도", postLocation2: "730", codeNm: "함안군" },
    { postLocation1: "경상남도", postLocation2: "740", codeNm: "창녕군" },
    { postLocation1: "경상남도", postLocation2: "820", codeNm: "고성군" },
    { postLocation1: "경상남도", postLocation2: "840", codeNm: "남해군" },
    { postLocation1: "경상남도", postLocation2: "850", codeNm: "하동군" },
    { postLocation1: "경상남도", postLocation2: "860", codeNm: "산청군" },
    { postLocation1: "경상남도", postLocation2: "870", codeNm: "함양군" },
    { postLocation1: "경상남도", postLocation2: "880", codeNm: "거창군" },
    { postLocation1: "경상남도", postLocation2: "890", codeNm: "합천군" },
    { postLocation1: "제주특별자치도", postLocation2: "110", codeNm: "제주시" },
    {
      postLocation1: "제주특별자치도",
      postLocation2: "130",
      codeNm: "서귀포시",
    },
  ],
};
